//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LunarLambda.Data
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DefaultDatabaseStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DefaultDatabaseStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LunarLambda.Data.DefaultDatabaseStrings", typeof(DefaultDatabaseStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DPS.
        /// </summary>
        internal static string DamagePerSecond {
            get {
                return ResourceManager.GetString("DamagePerSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Civilizations.
        /// </summary>
        internal static string FactionDatabaseItemName {
            get {
                return ResourceManager.GetString("FactionDatabaseItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        internal static string False {
            get {
                return ResourceManager.GetString("False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friendly.
        /// </summary>
        internal static string FriendlyRelation {
            get {
                return ResourceManager.GetString("FriendlyRelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hostile.
        /// </summary>
        internal static string HostileRelation {
            get {
                return ResourceManager.GetString("HostileRelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neutral.
        /// </summary>
        internal static string NeutralRelation {
            get {
                return ResourceManager.GetString("NeutralRelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fore.
        /// </summary>
        internal static string ShipBeamFrontName {
            get {
                return ResourceManager.GetString("ShipBeamFrontName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        internal static string ShipBeamLeftName {
            get {
                return ResourceManager.GetString("ShipBeamLeftName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aft.
        /// </summary>
        internal static string ShipBeamRearName {
            get {
                return ResourceManager.GetString("ShipBeamRearName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starboard.
        /// </summary>
        internal static string ShipBeamRightName {
            get {
                return ResourceManager.GetString("ShipBeamRightName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beam Weapon.
        /// </summary>
        internal static string ShipBeamWeaponName {
            get {
                return ResourceManager.GetString("ShipBeamWeaponName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        internal static string ShipClassName {
            get {
                return ResourceManager.GetString("ShipClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Known Vessels.
        /// </summary>
        internal static string ShipDatabaseItemName {
            get {
                return ResourceManager.GetString("ShipDatabaseItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hull.
        /// </summary>
        internal static string ShipHullName {
            get {
                return ResourceManager.GetString("ShipHullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump Capable.
        /// </summary>
        internal static string ShipJumpDriveName {
            get {
                return ResourceManager.GetString("ShipJumpDriveName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missile Stores.
        /// </summary>
        internal static string ShipMissileStoresName {
            get {
                return ResourceManager.GetString("ShipMissileStoresName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missile Tube Load Time.
        /// </summary>
        internal static string ShipMissileTubesLoadName {
            get {
                return ResourceManager.GetString("ShipMissileTubesLoadName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missile Tubes.
        /// </summary>
        internal static string ShipMissleTubesName {
            get {
                return ResourceManager.GetString("ShipMissleTubesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Models (debug).
        /// </summary>
        internal static string ShipModelDebugName {
            get {
                return ResourceManager.GetString("ShipModelDebugName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Speed.
        /// </summary>
        internal static string ShipMoveSpeedName {
            get {
                return ResourceManager.GetString("ShipMoveSpeedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shields.
        /// </summary>
        internal static string ShipShieldName {
            get {
                return ResourceManager.GetString("ShipShieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string ShipSizeName {
            get {
                return ResourceManager.GetString("ShipSizeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub-class.
        /// </summary>
        internal static string ShipSubClassName {
            get {
                return ResourceManager.GetString("ShipSubClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn Speed.
        /// </summary>
        internal static string ShipTurnSpeedName {
            get {
                return ResourceManager.GetString("ShipTurnSpeedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warp Capable.
        /// </summary>
        internal static string ShipWarpDriveName {
            get {
                return ResourceManager.GetString("ShipWarpDriveName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Warp Speed.
        /// </summary>
        internal static string ShipWarpSpeedName {
            get {
                return ResourceManager.GetString("ShipWarpSpeedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        internal static string True {
            get {
                return ResourceManager.GetString("True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unaware.
        /// </summary>
        internal static string UnawareRelation {
            get {
                return ResourceManager.GetString("UnawareRelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
    }
}
