//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LunarLambda.Campaigns.Standard.Databases {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ScienceDataStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ScienceDataStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LunarLambda.Campaigns.Standard.Databases.ScienceDataStrings", typeof(ScienceDataStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asteroid.
        /// </summary>
        internal static string Asteroid {
            get {
                return ResourceManager.GetString("Asteroid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asteroids are minor planets, usually smaller than a few kilometers. Larger variants are sometimes refered to as planetoids..
        /// </summary>
        internal static string AsteroidDesc {
            get {
                return ResourceManager.GetString("AsteroidDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black Hole.
        /// </summary>
        internal static string BlackHole {
            get {
                return ResourceManager.GetString("BlackHole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A black hole is a point of supercondensed mass with a gravitational pull so powerful that not even light can escape it. It has no locally detectable features, and can only be seen indirectly by blocking the view and distorting its surroundings, creating a strange circular mirror image of the galaxy. The black disc in the middle marks the event horizon, the boundary where even light can&apos;t escape it anymore. 
        ///	
        ///On the sensors, a black hole appears as a disc indicating the zone where the gravitational pull i [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BlackHoleDesc {
            get {
                return ResourceManager.GetString("BlackHoleDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blast radius.
        /// </summary>
        internal static string BlastRadius {
            get {
                return ResourceManager.GetString("BlastRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burst.
        /// </summary>
        internal static string Burst {
            get {
                return ResourceManager.GetString("Burst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage at center of blast.
        /// </summary>
        internal static string CenterDamage {
            get {
                return ResourceManager.GetString("CenterDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage.
        /// </summary>
        internal static string Damage {
            get {
                return ResourceManager.GetString("Damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop distance.
        /// </summary>
        internal static string DropDistance {
            get {
                return ResourceManager.GetString("DropDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each.
        /// </summary>
        internal static string Each {
            get {
                return ResourceManager.GetString("Each", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage at edge of blast.
        /// </summary>
        internal static string EdgeDamage {
            get {
                return ResourceManager.GetString("EdgeDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ElectroMagnetic Pulse (EMP).
        /// </summary>
        internal static string EMP {
            get {
                return ResourceManager.GetString("EMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to he electromagnetic pulse missile (EMP) reproduces the disruptive effects of a nuclear explosion, but without the destructive properties. This causes it to only affect shields within its blast radius, leaving their hulls intact. The EMP missile is also smaller and easier to store than heavy nukes. Many captains (and pirates) prefer EMPs over nukes for these reasons, and use them to knock out targets&apos; shields before closing to disable them with focused beam fire..
        /// </summary>
        internal static string EMPDesc {
            get {
                return ResourceManager.GetString("EMPDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homing Missile.
        /// </summary>
        internal static string HomingMissile {
            get {
                return ResourceManager.GetString("HomingMissile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This target-seeking missile is the workhorse of many space combat arsenals. It&apos;s compact enough to be fitted on frigates, and packs enough punch to be used on larger ships, though usually in more than a single missile tube..
        /// </summary>
        internal static string HomingMissileDesc {
            get {
                return ResourceManager.GetString("HomingMissileDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High-Velocity Lead Impactor (HVLI).
        /// </summary>
        internal static string HVLI {
            get {
                return ResourceManager.GetString("HVLI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A high-velocity lead impactor (HVLI) fires a simple slug of lead at a high velocity. This weapon is usually found in simpler ships since it does not require guidance computers. This also means its projectiles fly in a straight line from its tube and can&apos;t pursue a target.
        ///
        ///Each shot from an HVLI fires a burst of 5 projectiles, which increases the chance to hit but requires precision aiming to be effective..
        /// </summary>
        internal static string HVLIDesc {
            get {
                return ResourceManager.GetString("HVLIDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mine.
        /// </summary>
        internal static string Mine {
            get {
                return ResourceManager.GetString("Mine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mines are often placed in defensive perimeters around stations. There are also old minefields scattered around the galaxy from older wars.
        ///
        ///Some fearless captains use mines as offensive weapons, but their delayed detonation and blast radius make this use risky at best..
        /// </summary>
        internal static string MineDesc {
            get {
                return ResourceManager.GetString("MineDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Natural Phenomena.
        /// </summary>
        internal static string NaturalCategory {
            get {
                return ResourceManager.GetString("NaturalCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nebula.
        /// </summary>
        internal static string Nebula {
            get {
                return ResourceManager.GetString("Nebula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nebulae are the birthing places of new stars. These gas fields, usually created by the death of an old star, slowly form new stars due to the gravitational pull of its gas molecules. Because of the ever-changing nature of gas nebulae, most radar and scanning technologies are unable to penetrate them. Science officers are therefore advised to rely on probes and visual observations.
        /// </summary>
        internal static string NebulaDesc {
            get {
                return ResourceManager.GetString("NebulaDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thermonuclear Warhead.
        /// </summary>
        internal static string Nuke {
            get {
                return ResourceManager.GetString("Nuke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A nuclear missile is similar to a homing missile in that it can seek a target, but it moves and turns more slowly and explodes a greatly increased payload. Its nuclear explosion spans 1U of space and can take out multiple ships in a single shot.
        ///
        ///Some captains oppose the use of nuclear weapons because their large explosions can lead to &apos;fragging&apos;, or unintentional friendly fire. Shields should protect crews from harmful radiation, but because these weapons are often used in the thick of battle, there&apos;s no [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NukeDesc {
            get {
                return ResourceManager.GetString("NukeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range.
        /// </summary>
        internal static string Range {
            get {
                return ResourceManager.GetString("Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger distance.
        /// </summary>
        internal static string TriggerDistance {
            get {
                return ResourceManager.GetString("TriggerDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Known Weapons.
        /// </summary>
        internal static string WeaponsCategory {
            get {
                return ResourceManager.GetString("WeaponsCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wormhole.
        /// </summary>
        internal static string Wormhole {
            get {
                return ResourceManager.GetString("Wormhole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A wormhole, also known as an Einstein-Rosen bridge, is a phenomena that connects two points of spacetime. Jump drives operate in a similar fashion, but instead of being created at will, a wormhole occupies a specific location in space. Objects that enter a wormhole instantaneously emerge from the other end, which might be anywhere from a few feet to thousands of light years away. 
        ///
        ///Wormholes are rare, and most can move objects in only one direction. Traversable wormholes, which are stable and allow for mo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WormholeDesc {
            get {
                return ResourceManager.GetString("WormholeDesc", resourceCulture);
            }
        }
    }
}
