//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LunarLambda.Host.Game {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ShipInfoStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ShipInfoStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LunarLambda.Host.Game.ShipInfoStrings", typeof(ShipInfoStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beam Count.
        /// </summary>
        internal static string BeamWeapons {
            get {
                return ResourceManager.GetString("BeamWeapons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combat Boost.
        /// </summary>
        internal static string CombatBoost {
            get {
                return ResourceManager.GetString("CombatBoost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FTLDriveType.
        /// </summary>
        internal static string FTLType {
            get {
                return ResourceManager.GetString("FTLType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None,Warp,Jump.
        /// </summary>
        internal static string FTLTypes {
            get {
                return ResourceManager.GetString("FTLTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel Capacity.
        /// </summary>
        internal static string FuelCapcity {
            get {
                return ResourceManager.GetString("FuelCapcity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impulse Acceleration.
        /// </summary>
        internal static string ImpulseAcceleration {
            get {
                return ResourceManager.GetString("ImpulseAcceleration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impulse Speed.
        /// </summary>
        internal static string ImpulseSpeed {
            get {
                return ResourceManager.GetString("ImpulseSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manuver Speed.
        /// </summary>
        internal static string ManuverSpeed {
            get {
                return ResourceManager.GetString("ManuverSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missile Storage.
        /// </summary>
        internal static string MissileStores {
            get {
                return ResourceManager.GetString("MissileStores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missile Count.
        /// </summary>
        internal static string MissileWeaponCount {
            get {
                return ResourceManager.GetString("MissileWeaponCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repair Crew Size.
        /// </summary>
        internal static string RepairCrew {
            get {
                return ResourceManager.GetString("RepairCrew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shield Banks.
        /// </summary>
        internal static string ShieldBanks {
            get {
                return ResourceManager.GetString("ShieldBanks", resourceCulture);
            }
        }
    }
}
