//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LunarLambda.GUI.Menus {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MenuRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MenuRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LunarLambda.GUI.Menus.MenuRes", typeof(MenuRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        internal static string DefaultServerName {
            get {
                return ResourceManager.GetString("DefaultServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string DefaultVariation {
            get {
                return ResourceManager.GetString("DefaultVariation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effects Volume.
        /// </summary>
        internal static string EffectsVolume {
            get {
                return ResourceManager.GetString("EffectsVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FSAA: off;FSAA: 2x;FSAA: 4x;FSAA: 8x.
        /// </summary>
        internal static string FSAA {
            get {
                return ResourceManager.GetString("FSAA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FTL Drive Type:.
        /// </summary>
        internal static string FTLType {
            get {
                return ResourceManager.GetString("FTLType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None;Default;Warp;Jump;Warp &amp; Jump.
        /// </summary>
        internal static string FTLTypes {
            get {
                return ResourceManager.GetString("FTLTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windowed;Maximized;Fullscreen.
        /// </summary>
        internal static string FullscreenModes {
            get {
                return ResourceManager.GetString("FullscreenModes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullscreen Toggle.
        /// </summary>
        internal static string FullscreenToggle {
            get {
                return ResourceManager.GetString("FullscreenToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Rules.
        /// </summary>
        internal static string GameRules {
            get {
                return ResourceManager.GetString("GameRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphics.
        /// </summary>
        internal static string Graphics {
            get {
                return ResourceManager.GetString("Graphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long Range Radar.
        /// </summary>
        internal static string LongRangeRadar {
            get {
                return ResourceManager.GetString("LongRangeRadar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Screen Options.
        /// </summary>
        internal static string MainScreenOptions {
            get {
                return ResourceManager.GetString("MainScreenOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music Playblack.
        /// </summary>
        internal static string MusicPlayback {
            get {
                return ResourceManager.GetString("MusicPlayback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled;All Stations;Main Screen Only.
        /// </summary>
        internal static string MusicPlaybackModes {
            get {
                return ResourceManager.GetString("MusicPlaybackModes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music Volume.
        /// </summary>
        internal static string MusicVolume {
            get {
                return ResourceManager.GetString("MusicVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string NoVariatioName {
            get {
                return ResourceManager.GetString("NoVariatioName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No variation selected, the scenario will run using the default settings..
        /// </summary>
        internal static string NoVariationDescription {
            get {
                return ResourceManager.GetString("NoVariationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per-System Damage.
        /// </summary>
        internal static string PerSystemDamage {
            get {
                return ResourceManager.GetString("PerSystemDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Ship Options.
        /// </summary>
        internal static string PlayerShipOptions {
            get {
                return ResourceManager.GetString("PlayerShipOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview Soundtrack.
        /// </summary>
        internal static string PreviewSoundtrack {
            get {
                return ResourceManager.GetString("PreviewSoundtrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        internal static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nominal Sensor Range:.
        /// </summary>
        internal static string RadarRange {
            get {
                return ResourceManager.GetString("RadarRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Complexity:.
        /// </summary>
        internal static string ScanComplexity {
            get {
                return ResourceManager.GetString("ScanComplexity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None (Delay);Normal;Advanced.
        /// </summary>
        internal static string ScanTypes {
            get {
                return ResourceManager.GetString("ScanTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenarios.
        /// </summary>
        internal static string Scenario {
            get {
                return ResourceManager.GetString("Scenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Configuration.
        /// </summary>
        internal static string ServerConfiguration {
            get {
                return ResourceManager.GetString("ServerConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server IP:.
        /// </summary>
        internal static string ServerIP {
            get {
                return ResourceManager.GetString("ServerIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Name:.
        /// </summary>
        internal static string ServerName {
            get {
                return ResourceManager.GetString("ServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Password:.
        /// </summary>
        internal static string ServerPassword {
            get {
                return ResourceManager.GetString("ServerPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Visibility:.
        /// </summary>
        internal static string ServerVis {
            get {
                return ResourceManager.GetString("ServerVis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lan Only;Internet.
        /// </summary>
        internal static string ServerVisModes {
            get {
                return ResourceManager.GetString("ServerVisModes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound Options.
        /// </summary>
        internal static string SoundOptions {
            get {
                return ResourceManager.GetString("SoundOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Client.
        /// </summary>
        internal static string StartClient {
            get {
                return ResourceManager.GetString("StartClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Scenario.
        /// </summary>
        internal static string StartScenario {
            get {
                return ResourceManager.GetString("StartScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Server.
        /// </summary>
        internal static string StartServer {
            get {
                return ResourceManager.GetString("StartServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tactical Radar.
        /// </summary>
        internal static string TacticalRadar {
            get {
                return ResourceManager.GetString("TacticalRadar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorials.
        /// </summary>
        internal static string Tutorials {
            get {
                return ResourceManager.GetString("Tutorials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variation:.
        /// </summary>
        internal static string Variation {
            get {
                return ResourceManager.GetString("Variation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapon Frequenceies.
        /// </summary>
        internal static string WeaponFrequencies {
            get {
                return ResourceManager.GetString("WeaponFrequencies", resourceCulture);
            }
        }
    }
}
