//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LunarLambda.Campaigns.Standard {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FactionStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FactionStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LunarLambda.Campaigns.Standard.FactionStrings", typeof(FactionStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arlenians.
        /// </summary>
        internal static string Arlenian {
            get {
                return ResourceManager.GetString("Arlenian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arlenians are energy-based life forms who long ago transcended physical reality through superior technology. Arlenians&apos; energy forms also give them access to strong telepathic powers. Many consider Arlenians to be the first and oldest explorers of the galaxy.
        ///
        ///Despite all these advantages, they are very peaceful, as they see little value in material posession.
        ///
        ///For unknown reasons, Arlenians started granting their anti-grav technology to other races, and almost all starfaring races&apos; technology is based  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ArlenianDesc {
            get {
                return ResourceManager.GetString("ArlenianDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exuari.
        /// </summary>
        internal static string Exuari {
            get {
                return ResourceManager.GetString("Exuari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exuari are race of predatory amphibians with long noses. They once had an empire that stretched halfway across the galaxy, but their territory is now limited to a handful of star systems. For some reason, they find death to be outrageously funny, and several of their most famous comedians have died on stage.
        ///
        ///Upon making contact with other races, the chaotic Exuari found that killing aliens is more fun than killing their own people, and as such attack all non-Exauri on sight..
        /// </summary>
        internal static string ExuariDesc {
            get {
                return ResourceManager.GetString("ExuariDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghosts.
        /// </summary>
        internal static string Ghosts {
            get {
                return ResourceManager.GetString("Ghosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Ghosts, an abbreviation of &quot;ghosts in the machine&quot;, are the result of complex artificial intelligence experiments. While no known race has intentionally created such intelligences, some AIs have come about by accident. None of the factions claim to have had anything to do with such experiments, in part out of fear that it would give the others too much insight into their research programs. This &quot;don&apos;t ask, don&apos;t tell&quot; policy does little but aid the Ghosts&apos; agenda.
        ///
        ///What little is known about the Ghost [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GhostsDesc {
            get {
                return ResourceManager.GetString("GhostsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Human Navy.
        /// </summary>
        internal static string HuNav {
            get {
                return ResourceManager.GetString("HuNav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The remnants of the human navy.
        ///
        ///While all other races were driven to the stars out of greed or scientific research, humans where the only race to start exploring the galaxy because their homeworld could no longer sustain their population. Some other races view humans as a sort of virus or plague due to the rate at which they can breed and spread.
        ///
        ///Due to human regulations on spaceships, naval ships are the only ones permitted in deep space. However, this hasn&apos;t completely prevented humans outside of th [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HuNavDesc {
            get {
                return ResourceManager.GetString("HuNavDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Independent.
        /// </summary>
        internal static string Independent {
            get {
                return ResourceManager.GetString("Independent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Despite appearing as a faction, independents are distinguished primarily by having no strong affiliation with any faction at all. Most traders consider themselves independent, though certain voices have started to speak up about creating a merchant faction..
        /// </summary>
        internal static string IndependentDesc {
            get {
                return ResourceManager.GetString("IndependentDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kraylor.
        /// </summary>
        internal static string Kraylor {
            get {
                return ResourceManager.GetString("Kraylor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reptilian Kraylor are a race of warriors with a strong religious dogma.
        ///
        ///As soon as the Kraylor obtained reliable space flight, they immediately set out to conquer and subjugate unbelievers. Their hierarchy is based solely on physical might; a Kraylor kills anything it can kill, and owns anything it can take by force.
        ///
        ///Kraylor can live for weeks without air, food, or gravity, and consider humans to be weak creatures for dying within minutes of exposure to space. Because of their fortitude and cultur [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string KraylorDesc {
            get {
                return ResourceManager.GetString("KraylorDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ktlitans.
        /// </summary>
        internal static string Ktlitan {
            get {
                return ResourceManager.GetString("Ktlitan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Ktlitans are intelligent eight-legged creatures that resemble Earth&apos;s arachnids. However, unlike most terrestrial arachnids, the Ktlitans do not fight amogn themselves. Their common, and only, goal is their species&apos;s survival.
        ///
        ///While they live in a hierarchical structure that resembles a hive, the lower castes continue their work and start new tasks on their own even when no orders come from their superiors. However, when higher castes are present, the lower Ktlitans follow their orders without questi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string KtlitansDesc {
            get {
                return ResourceManager.GetString("KtlitansDesc", resourceCulture);
            }
        }
    }
}
