//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LunarLambda.Campaigns.Standard {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LunarLambda.Campaigns.Standard.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Atlantis X23 is the smallest model of destroyer, and its combination of frigate-like size and corvette-like power makes it an excellent escort ship when defending larger ships against multiple smaller enemies. Because the Atlantis X23 is fitted with a jump drive, it can also serve as an intersystem patrol craft..
        /// </summary>
        internal static string Corvette_AtlantisX32Description {
            get {
                return ResourceManager.GetString("Corvette_AtlantisX32Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atlantis X23.
        /// </summary>
        internal static string Corvette_AtlantisX32Name {
            get {
                return ResourceManager.GetString("Corvette_AtlantisX32Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mark 4 Adder is a rare sight these days due to the success its successor, the mark 5 Adder, which often replaces this model.Its similar hull, however, means careless buyers are sometimes conned into buying mark 4 models disguised as the mark 5..
        /// </summary>
        internal static string Fighter_AdderMk4Description {
            get {
                return ResourceManager.GetString("Fighter_AdderMk4Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adder Mk. IV.
        /// </summary>
        internal static string Fighter_AdderMk4Name {
            get {
                return ResourceManager.GetString("Fighter_AdderMk4Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Adder line&apos;s fifth iteration proved to be a great success among pirates and law officers alike. It is cheap, fast, and easy to maintain, and it packs a decent punch..
        /// </summary>
        internal static string Fighter_AdderMk5Description {
            get {
                return ResourceManager.GetString("Fighter_AdderMk5Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adder Mk. V.
        /// </summary>
        internal static string Fighter_AdderMk5Name {
            get {
                return ResourceManager.GetString("Fighter_AdderMk5Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mark 6 Adder is a small upgrade compared to the highly successful mark 5 model.Since people still prefer the more familiar and reliable mark 5, the mark 6 has not seen the same level of success..
        /// </summary>
        internal static string Fighter_AdderMk6Description {
            get {
                return ResourceManager.GetString("Fighter_AdderMk6Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adder Mk. VI.
        /// </summary>
        internal static string Fighter_AdderMk6Name {
            get {
                return ResourceManager.GetString("Fighter_AdderMk6Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MT52 Hornet is a basic interceptor found in many corners of the galaxy.It&apos;s easy to find spare parts for MT52s, not only because they are produced in large numbers, but also because they suffer high losses in combat..
        /// </summary>
        internal static string Fighter_HornetDescription {
            get {
                return ResourceManager.GetString("Fighter_HornetDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MU52 Hornet is a new, upgraded version of the MT52. All of its systems are slightly improved over the MT52 model..
        /// </summary>
        internal static string Fighter_HornetMk2Description {
            get {
                return ResourceManager.GetString("Fighter_HornetMk2Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MU52 Hornet Mk. II.
        /// </summary>
        internal static string Fighter_HornetMk2Name {
            get {
                return ResourceManager.GetString("Fighter_HornetMk2Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MP52 Hornet is a significantly upgraded version of MU52 Hornet, with nearly twice the hull strength, nearly three times the shielding, better acceleration, impulse boosters, and a second laser cannon..
        /// </summary>
        internal static string Fighter_HornetMk3Description {
            get {
                return ResourceManager.GetString("Fighter_HornetMk3Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MP52 Hornet Mk. III.
        /// </summary>
        internal static string Fighter_HornetMk3Name {
            get {
                return ResourceManager.GetString("Fighter_HornetMk3Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MT52 Hornet.
        /// </summary>
        internal static string Fighter_HornetName {
            get {
                return ResourceManager.GetString("Fighter_HornetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The WX - Lindworm, or &quot;Worm&quot; as it&apos;s often called, is a bomber-class starfighter. While one of the least-shielded starfighters in active duty, the Worm&apos;s two launchers can pack quite a punch.Its goal is to fly in, destroy its target, and fly out or be destroyed..
        /// </summary>
        internal static string Fighter_LindwormDescription {
            get {
                return ResourceManager.GetString("Fighter_LindwormDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WX-Lindworm.
        /// </summary>
        internal static string Fighter_LindwormName {
            get {
                return ResourceManager.GetString("Fighter_LindwormName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The size of a sprawling town, stations at this scale represent a faction&apos;s center of space-borne power in a region. They serve many functions at once and represent an extensive investment of time, money, and labor. A huge station&apos;s shields and thick hull can keep it intact long enough for reinforcements to arrive, even when faced with an ongoing siege or massive, perfectly coordinated assault..
        /// </summary>
        internal static string HugeStationDescription {
            get {
                return ResourceManager.GetString("HugeStationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Huge Station.
        /// </summary>
        internal static string HugeStationName {
            get {
                return ResourceManager.GetString("HugeStationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These space-borne communities often represent permanent bases in a sector.Stations of this size can be military installations, commercial hubs, deep - space settlements, and small shipyards.Only a concentrated attack can penetrate a large station&apos;s shields, and its hull can withstand all but the most powerful weaponry..
        /// </summary>
        internal static string LargeStationDescription {
            get {
                return ResourceManager.GetString("LargeStationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large Station.
        /// </summary>
        internal static string LargeStationName {
            get {
                return ResourceManager.GetString("LargeStationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large enough to accommodate small crews for extended periods of times, stations of this size are often trading posts, refueling bases, mining operations, and forward military bases.While their shields are strong, concerted attacks by many ships can bring them down quickly..
        /// </summary>
        internal static string MediumStationDescription {
            get {
                return ResourceManager.GetString("MediumStationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium Station.
        /// </summary>
        internal static string MediumStationName {
            get {
                return ResourceManager.GetString("MediumStationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stations of this size are often used as research outposts, listening stations, and security checkpoints.Crews turn over frequently in a small station&apos;s cramped accommodations, but they are small enough to look like ships on many long-range sensors, and organized raiders sometimes take advantage of this by placing small stations in nebulae to serve as raiding bases. They are lightly shielded and vulnerable to swarming assaults..
        /// </summary>
        internal static string SmallStationDescription {
            get {
                return ResourceManager.GetString("SmallStationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small Station.
        /// </summary>
        internal static string SmallStationName {
            get {
                return ResourceManager.GetString("SmallStationName", resourceCulture);
            }
        }
    }
}
